### PR TITLE
add advanced section + web_sys discussion

### PR DESCRIPTION
**Pull request by blorbb**
Just thought to add this after I spent way too long figuring out web-sys :). I'm not 100% sure that everything I've mentioned here is true, so please point out any errors you may find.

Covers part of #22 and starts on #8 

I'm not sure if this should be part of the advanced section - feel free to request changes if you think it would fit better somewhere else, or if you want to change the text on the advanced intro page.

Some extra notes:
- Is cloning a `web_sys::HtmlElement` actually cheap? I tried to look at the source code but I can't tell what's happening, everything is a macro.
- Should I format the text so that a paragraph isn't on one long line? I just wrote this with word wrap on so it looks fine in my editor, but I noticed that some other pages use line breaks. What formatter + settings should I use if so?

Also, feel free to make any minor nitpicks, I'm happy to make any tiny changes (+ improve my writing!)

### CODE REVIEW

**Comment by diversable** [comment]
First off, I just wanted to say thank you for taking the time to write this up!! 
I think you did a good job explaining how/why/when one would use `web_sys` with Leptos. 

For Discussion:
I do wonder though whether dealing with web_sys / js_sys  tasks are common enough that this should be near the end of Part 1 of the book?? 
Basically, is knowledge about `web_sys` & `js_sys` required for building a full, production-level CSR app? 

If so, we should probably move this section to part 1, which is all about building UI's with Leptos..

What do you guys think..??


P.S. in terms of formatting..
there isn't a formal formatter that I/we have been using. What I've been doing personally is just putting each individual sentence on a new line - I think it makes it easier to reference particular sentences in discussions (and also gives you visual feedback if your sentences get really long, like mine sometimes do 😋 ).

**Comment by blorbb** [comment]
looking at the discord, this seems semi-common so I'll move it to the end of part 1. I'll remove the advanced section too for now, since there aren't any topics in it.

**Comment by blorbb** [comment]
(@diversable actually did you mean end of part 1 as in like after section 11, or the end of section "3. Part 1: ..."? I can move it again if you think it'll fit better after section 11)

**Comment by blorbb** [comment]
Should be ready now, thanks for helping out!

**Pull request merged**
