### PR TITLE
Update Section 15.1. An Important Note on Security

### PR DESCRIPTION
**Pull request by aschweig**
The existing language "You should never return something sensitive from a server function."  This text suggests it is impossible to make a server function secure.  This commit indicates two necessary steps making a server function appropriate for sensitive data.

This edit is intentionally narrow and minimal.  Is there an appropriate link to provide here to expand on the topic?

### CODE REVIEW

**Comment by aschweig** [comment]
My issue is that this language could be particularly off-putting to PHBs looking into adopt leptos.

Maybe language like the following,

_Server functions are public APIs and carry associated risks. Never return sensitive information from a server function unless it's properly secured. At a minimum, server functions should authenticate requests and the framework should employ adequate encryption._

**Comment by aschweig** [comment]
I'm taking another stab at this:

_Server functions are public APIs with inherent risks. Never return sensitive information from a server function unless these risks are addressed. Minimally, server functions should authenticate requests, employ adequate encryption, and ensure that no user can use to API to extract unauthorized data, engage in privilege escalation, or otherwise disable or compromise the service._

**Comment by benwis** [comment]
Hmm, perhaps "Server functions create a public API endpoint. Do not return information from a server function unless it is public, or you've implemented proper security procedures. These procedures might include authenticating incoming requests, ensuring proper encryption, rate limiting access, and more.

**Comment by aschweig** [comment]
> Hmm, perhaps "Server functions create a public API endpoint. Do not return information from a server function unless it is public, or you've implemented proper security procedures. These procedures might include authenticating incoming requests, ensuring proper encryption, rate limiting access, and more.

I liked this so I updated the PR to reflect this language.

**Comment by benwis** [comment]
Thank you!

**Pull request merged**
