### PR TITLE
Fix typo: 'Form' to 'form' since it is a HTML element

### PR DESCRIPTION
**Pull request by NCura**

### CODE REVIEW

**Comment by gbj** [comment]
This should actually read `<FancyForm/>` instead of `<Form/>`, given the context in the sentence before:
> For example, imagine I have a `<FancyForm/>` component
that enhances an HTML `<form>`. I need some way to pass all its inputs.

**Comment by NCura** [comment]
I initially misunderstood the code example, thinking it was the body of the FancyForm component function, which made the previous sentence unclear. Changing "Form" to "FancyForm" clarifies everything. Can I update this pull request to fix the typo correctly (I don't know if that is even a thing), or should I close it and create a new one with the correct fix?

**Comment by gbj** [comment]
Just updating this PR is great :-)

**Comment by NCura** [comment]
Done!

**Pull request merged**
